---
dhcp_server_config:
  subnet4:
    - id: 1
      subnet: 10.1.0.0/24
      pools:
        - start: 10.1.0.200
          end: 10.1.0.250
      option_data:
        - name: routers
          data: 10.1.0.254
        - name: domain-name-servers
          data: 10.0.0.101,10.0.0.102
        - name: domain-search
          data: lab.lan
