---
bind9_config:
  zones:
    - name: lab.lan
      type: primary
      peer_ip:
        - 10.0.0.102
      sub_domains:
        - name: dev.lab.lan
          type: forward
          role: primary
          peer_ip:
            - 10.0.0.102
          name_servers:
            - name: dns-03
              ip_address: 10.2.0.101
            - name: dns-04
              ip_address: 10.2.0.102
      mname: dns-01
      name_servers:
        - name: dns-01
          ip_address: 10.0.0.101
        - name: dns-02
          ip_address: 10.0.0.102
  options:
    forwarders:
      - 8.8.8.8
      - 1.1.1.1
    allowed_networks:
      - 10.0.0.0/8
      - 192.168.0.0/16
      - localhost
    query_log: yes
    recursion: yes
