---
bind9_config:
  zones:
    - name: dev.lab.lan
      type: forward
      role: primary
      peer_ip:
        - 10.2.0.102
      mname: dns-03
      name_servers:
        - name: dns-03
        - name: dns-04
  options:
    forwarders:
      - 10.0.0.101
      - 10.0.0.102
    allowed_networks:
      - 10.0.0.0/8
      - 192.168.0.0/16
      - localhost
    query_log: yes
    recursion: yes
