ubuntu:
  hosts:
    dns-0[1:2].lab.lan:
    staging-0[1:2].lab.lan:
    sandbox-01.lab.lan:
    zabbix-01.lab.lan:
    docker-01.lab.lan:
    ca-01.lab.lan:
    dhcp-01.lab.lan:
dns:
  hosts:
    dns-0[1:2].lab.lan:
staging:
  hosts:
    staging-0[1:2].lab.lan:
zabbix:
  hosts:
    zabbix-01.lab.lan:
docker:
  hosts:
    docker-01.lab.lan:
cert_auth:
  hosts:
    ca-01.lab.lan:
dhcp:
  hosts:
    dhcp-01.lab.lan:
test:
  hosts:
    sandbox-01.lab.lan:
  children:
    staging:
prod:
  children:
    dns:
    zabbix:
    docker:
    cert_auth:
    dhcp: