---
- name: Load OS-specific vars.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_facts.distribution}}.yml'
        - '{{ansible_facts.os_family}}.yml'
        - main.yml
      paths:
        - 'vars'

- name: install packages
  ansible.builtin.package:
    name: "{{item}}"
    update_cache: true
  become: true
  loop: "{{packages}}"

- include_tasks: zabbix_agent.yml
...
