---
- name: zabbix deb file containing repo
  ansible.builtin.package:
    deb: "{{ zabbix_repo }}"
  become: true

- name: install zabbix agent
  ansible.builtin.package:
    name: zabbix-agent
    update_cache: true
  become: true
  notify: restart zabbix agent

- name: copy config file
  ansible.builtin.copy:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/
  become: true
  notify: restart zabbix agent
