---
# need to load a yml file for each zone
# unsure how to do it
# yml file is defined in the host vars under
# bind9_config.zones.record_file

# - name: import dns records
#   ansible.builtin.include_vars:
#     file: records.yml

- name: db files containing records
  ansible.builtin.template:
    src: db.j2
    dest: /etc/bind/db.{{ item.name }}
    owner: root
    group: bind
    mode: 0644
    backup: true
  loop: "{{ bind9_config.zones }}"
  notify: restart named
  become: true
