---
- name: Update Packages
  ansible.builtin.apt:
    force_apt_get: true
    update_cache: true
    upgrade: dist
  become: true
  register: update_packages

- name: debug update packages
  ansible.builtin.debug:
    msg: "{{update_packages}}"
    verbosity: 1
