- name: ansible user
  ansible.builtin.user:
    name: ansible
    state: present
    password: $6$dnBiRvHwrVE$WfnhgkLcd/tpfd87rlyRhz8NKQiuS9FcharErlLgOOQhVLi2FezHq5N99a7JfRfImnlvh.NkoFbzPqTQjjZqI/
    groups: adm, sudo
    append: false
    shell: /bin/bash
  become: true

- name: my personal user
  ansible.builtin.user:
    name: harry
    state: present
    password: $6$JWy2mMnn9c5hDSTz$HHDR9RSbYhyYYDzTiRKxOkX60NHFgLTU2Ym3ZJC9S2kUmCZV93oJAACDyup.HInDEMWw4RoBrMyWi9jvyGUVc.
    shell: /bin/bash
  become: true