---
plugin: netbox.netbox.nb_inventory
api_endpoint: https://docker-01.lab.lan:8000
token: c2dbe0246d10dffc2c1ce816d5d474107a931414
validate_certs: false
group_by:
  - tags
  - platforms
compose:
  foo: last_updated
