---
plugin: community.general.proxmox
url: https://pve.lab.lan:8006
user: api_user@pve
password: "{{ lookup('ansible.builtin.env','PROXMOX_PASSWORD')}}"
validate_certs: false
want_facts: true
keyed_groups:
    # proxmox_tags_parsed is an example of a fact only returned when 'want_facts=true'
  - key: proxmox_tags_parsed
    separator: ""
    prefix: group
groups:
  ansible: "'ansible' in (proxmox_tags_parsed|list)"
  test: "'test' in (proxmox_tags_parsed|list)"
