---
- name: Load OS-specific vars.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_facts.distribution}}.yml'
        - '{{ansible_facts.os_family}}.yml'
        - main.yml
      paths:
        - 'vars'

# tasks file for standard_configs
- include_tasks: timezone.yml
- include_tasks: users.yml
- include_tasks: rsa_keys.yml
- include_tasks: ssh.yml
