---
- name: configuring key for user 'harry'
  ansible.posix.authorized_key:
    user: harry
    key: "{{ lookup('file', 'public-harry') }}"
    state: present
  become: true

- name: configuring key for user 'ansible'
  ansible.posix.authorized_key:
    user: ansible
    key: "{{ lookup('file', 'public-ansible') }}"
    state: present
