---
- name: ansible user
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.password }}"
    groups: "{{ default_groups }}"
    append: false
    shell: /bin/bash
  become: true
  with_items: "{{ users }}"
