---
- name: ansible user
  ansible.builtin.user:
    name: ansible
    state: present
    password: "{{ ansible_local_user_pass }}"
    groups: "{{ default_groups }}"
    append: false
    shell: /bin/bash
  become: true

- name: my personal user
  ansible.builtin.user:
    name: harry
    state: present
    password: "{{ harry_local_user_pass }}"
    groups: "{{ default_groups }}"
    shell: /bin/bash
  become: true
