---
- name: backup database
  ansible.builtin.shell:
    chdir: "{{ install_directory }}"
    cmd: "{{ backup_database_command }}"

- name: pull backup from node
  ansible.builtin.fetch:
    src: "{{ install_directory }}/{{ backup_file }}"
    dest: "{{ database_backup_location }}"
    flat: true

- name: delete backup file from node
  ansible.builtin.file:
    path: "{{ install_directory }}/{{ backup_file }}"
    state: absent
