---
- name: clone git repository
  ansible.builtin.git:
    clone: true
    repo: "{{ git_repo }}"
    dest: "{{ netbox_dir }}"
    version: release

- name: create docker-compose.override.yml
  ansible.builtin.template:
    src: netbox_docker_docker-compose.override.yml.j2
    dest: "{{ netbox_dir }}/docker-compose.override.yml"
    owner: root
    group: root
    mode: "0644"

- name: docker compose up
  community.docker.docker_compose_v2:
    project_src: "{{ netbox_dir }}"
    state: present
