---
# tasks file for docker_containers

- name: install netbox
  include_tasks: install.yml
  when: netbox_docker is defined and netbox_docker | bool

- name: backup netbox
  include_tasks: backup.yml
  when: netbox_docker_backup is defined and netbox_docker_backup | bool

- name: restore netbox
  include_tasks: restore.yml
  when: netbox_docker_restore is defined and netbox_docker_restore | bool

- name: update netbox
  include_tasks: update.yml
  when: update is defined and update | bool
