---
- name: copy db file
  ansible.builtin.copy:
    src: "{{ database_backup_location }}"
    dest: "{{ install_directory }}"
    owner: root
    group: root
    mode: "0644"

- name: docker compose down required containers
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}"
    services:
      - netbox
      - netbox-worker
    state: stopped

- name: restore database
  ansible.builtin.shell:
    chdir: "{{ install_directory }}"
    cmd: "{{ restore_database_command }}"

- name: docker compose up
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}"
    services:
      - netbox
      - netbox-worker
    state: present

- name: clean up
  ansible.builtin.file:
    path: "{{ install_directory }}/{{ backup_file }}"
    state: absent
