---
- name: copy db file
  ansible.builtin.copy:
    src: "{{ database_backup_location }}"
    dest: "{{ netbox_dir }}"
    owner: root
    group: root
    mode: "0644"

- name: docker compose down required containers
  community.docker.docker_compose_v2:
    project_src: "{{ netbox_dir }}"
    services:
      - netbox
      - netbox-worker
    state: stopped

- name: restore database
  ansible.builtin.shell:
    chdir: "{{ netbox_dir }}"
    cmd: "{{ netbox_docker_restore_database_command }}"

- name: docker compose up
  community.docker.docker_compose_v2:
    project_src: "{{ netbox_dir }}"
    services:
      - netbox
      - netbox-worker
    state: present

- name: clean up
  ansible.builtin.file:
    path: "{{ netbox_dir }}/db_dump.sql.gz"
    state: absent
