---
# tasks file for roles/docker_containers

- name: set var images
  ansible.builtin.set_fact:
    images: "{{ images }}"
  when: images is defined

- name: set var containers
  ansible.builtin.set_fact:
    containers: "{{ containers }}"
  when: containers is defined

- include_tasks: docker_images.yml
  loop: "{{ images }}"
  when: images is defined

- include_tasks: docker_containers.yml
  loop: "{{ containers }}"
  when: containers is defined
