---
# tasks file for roles/updates
- name: load os-specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ansible_facts.distribution}}.yml"
        - "{{ansible_facts.os_family}}.yml"
        - main.yml
      paths:
        - "vars"

- name: proxmox snapshot
  community.proxmox.proxmox_snap:
    hostname: "{{inventory_hostname}}"
    state: present
    vmstate: true
  delegate_to: localhost

- name: update
  block:
    - include_tasks: update.yml

    - include_tasks: reboot_{{ ansible_facts.os_family }}.yml

    - include_tasks: verification/base_verification.yml

    - include_tasks: "verification/{{ verification }}"
      when: verification is defined
  rescue:
    - name: revert snapshot
      community.proxmox.proxmox_snap:
        hostname: "{{inventory_hostname}}"
        state: rollback
      delegate_to: localhost
  always:
    - name: remove snapshot
      community.proxmox.proxmox_snap:
        hostname: "{{inventory_hostname}}"
        state: absent
      delegate_to: localhost
