---
# tasks file for roles/updates

- name: update ubuntu
  block:
    - include_tasks: update_ubuntu.yml
      when: ansible_facts.os_family == 'Debian'

    - include_tasks: reboot_ubuntu.yml
      when: ansible_facts.os_family == 'Debian'

- name: verification scripts
  block:
    - include_tasks: verification.yml
      when: verification is defined
