---
zabbix_repo: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.4+ubuntu24.04_all.deb
zabbix_link_templates:
  - ICMP Ping
  - Linux by Zabbix agent
