#!/usr/bin/env ansible-playbook
---
- name: configuring keys for ssh using authorized_keys
  hosts: tags_testing
  gather_facts: false

  tasks:
    - name: configuring key for user 'harry'
      ansible.posix.authorized_key:
        user: harry
        key: "{{ lookup('file', 'public-harry') }}"
        state: present
      become: true

    - name: configuring key for user 'ansible'
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ lookup('file', 'public-ansible') }}"
        state: present
