---
- name: configuration context
  connection: local
  hosts: localhost
  gather_facts: false

  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API')}}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN')}}"
    vm_name: "host-97"
    vm_value: "127.0.0.33"
    vm_type: "A"
    vm_delete_key: "host-98"
    domain_name: "example.local"
           

  tasks:
    - name: get config context
      netbox.netbox.netbox_config_context:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "test_config_context"
          data:
        state: present
      register: result

    - name: temp dict for new host values in dict for new host
      ansible.builtin.set_fact:
        test_dict:
          type: "{{ vm_type | default('A') }}"
          value: "{{ vm_value }}"

    - name: list for new vm
      ansible.builtin.set_fact:
        ll:
          - key: "{{ vm_name }}"
            value: "{{ test_dict }}"

    - name: adding {{ vm_name }} to {{ domain_name }}
      ansible.builtin.set_fact:
        temp_host_dict: "{{ ll | items2dict }}"
    
    - name: set current_hosts
      ansible.builtin.set_fact:
        current_hosts: "{{ result.config_context.data.domains[domain_name] | combine(temp_host_dict) }}"
  
    - name: set dict for config_context
      set_fact:
        temp_dict_1:
          - key: "{{ domain_name }}"
            value: "{{ current_hosts }}"

    - name: set dict
      set_fact:
        temp_dict_1: "{{ temp_dict_1 | items2dict}}"

    - name: final_config_context
      ansible.builtin.set_fact:
        final_config_context: "{{result.config_context.data | combine({'domains' :temp_dict_1})}}"

    - name: update config context
      netbox.netbox.netbox_config_context:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "test_config_context"
          data: "{{ final_config_context }}"
        state: present
      register: result