- name: transfer public key to hosts
  gather_facts: false
  hosts: all_ubuntu_servers

  tasks:
    - name: transfer key
      ansible.builtin.copy:
        src: ../templates/my_public_key
        dest: /home/harry/.ssh/authorized_keys
      become: True