- name: copying named configuration to each dns host
  gather_facts: true
  hosts: dns

  handlers:
    - name: restart named
      service:
        name: named
        state: restarted

  tasks:
    - name: backup existing named.conf
      ansible.builtin.fetch:
        dest: /home/harry/ansible/homelab/backups
        src: /etc/bind/named.conf

    - name: copy named.conf file from template
      ansible.builtin.template:
        src: named.conf.{{ansible_hostname}}.lab.lan
        dest: /etc/bind/named.conf
      become: true
      notify: restart named
