#!/usr/bin/env ansible-playbook
---
- name: install docker on docker servers
  hosts: tags_docker,tags_cert_auth

  roles:
    - role: geerlingguy.docker
  become: true

- name: install ejbca docker container
  hosts: tags_cert_auth

  roles:
    - role: ejbca_docker
  become: true