- name: Reboot Servers
  hosts: all
  gather_facts: false
  
  tasks:
    - name: include update task
      include_tasks: tasks/reboot_server.yaml

    - name: debug reboot
      ansible.builtin.debug:
        msg: "{{reboot}}"