- name: Reboot Servers If Required
  gather_facts: false
  hosts: all

  tasks:
    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      ansible.builtin.stat: path=/run/reboot-required get_md5=no
      register: reboot_required_file

    - name: include reboot task
      include_tasks: tasks/reboot_server.yaml

    - name: debug reboot
      ansible.builtin.debug:
        msg: "{{reboot}}"