- name: scratch playbook
  hosts: dns-02.lab.lan
  gather_facts: false

  tasks:

  - name: verify dns
    ansible.builtin.systemd_service:
      name: named.service
      state: started
    register: status

  - name: debug
    ansible.builtin.debug:
      msg: "{{ status }}"
  