#!/usr/bin/env ansible-playbook
---
- name: standardized apps and configurations for all servers
  hosts: tags_ansible
  strategy: free

  roles:
    - role: standard_configs
    - role: standard_apps

