#!/usr/bin/env ansible-playbook
---
- name: standardized apps and configurations for all servers
  hosts: tags_ansible

  roles:
    - role: standard_apps
    - role: standard_configs

- name: install docker on docker servers
  hosts: tags_docker

  roles:
    - role: geerlingguy.docker
  become: true
