#!/usr/bin/env ansible-playbook
---
- name: netbox testing
  hosts: localhost
  gather_facts: false
  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API')}}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN')}}"    
  
  tasks:
    # the set rand_vm_name and set vm_name tasks allows the vm_name to be specified by 
    # command line -e argument if a non random name is required
    # | first on query() returns the first character even though it is a list when assigned to the variable
    - name: set rand_vm_name
      ansible.builtin.set_fact:
        rand_vm_name: "{{ query('community.general.random_string', upper=false, special=false, length = 15) }}"
      when: vm_name is not defined

    - name: set vm_name
      ansible.builtin.set_fact:
        vm_name: "{{ rand_vm_name[0] }}"
      when: vm_name is not defined

    - name: set fqdn
      ansible.builtin.set_fact:
        fqdn: "{{ vm_name | first }}.{{ searchdomains | first }}"

    - name: netbox vm
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ vm_name }}"
          # primary_ip4: "{{ ip_info.ip_address }}" # cant do this here
          cluster: "homelab"
          platform: "{{ netbox_platform }}"
          tags: "{{ netbox_tags }}"
        state: present
        
        # have to create vm interface to then assign the ip address
    - name: netbox vm interface
      netbox.netbox.netbox_vm_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "primary"
          virtual_machine: "{{ vm_name }}"
        state: present

    - name: get netbox vm ip_address
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: "{{ prefix }}"
          assigned_object:
            virtual_machine: "{{ vm_name }}"
            name: "primary"
          dns_name: "{{ fqdn }}"
        state: new
      register: new_ip

    # can't assign primary ip to virtual machine until the ip address is created
    - name: netbox primary_ip4
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ vm_name }}"
          primary_ip4: "{{ new_ip.ip_address.address }}"

    - name: clone template
      community.proxmox.proxmox_kvm:
        name: "{{ vm_name }}"
        clone: "{{ netbox_platform }}"
        node: pve
        state: present
        update_unsafe: true
      register: cloned_vm
    
    # i had trouble with configuring the vm in the same task as cloning it
    # my solution is to clone it in one task and configure it in another one
    - name: configure virtual machine
      community.proxmox.proxmox_kvm:
        vmid: "{{ cloned_vm.vmid }}"
        # name: "{{ vm_name }}"
        node: pve
        ipconfig:
          ipconfig0: "ip={{ new_ip.ip_address.address }},gw={{ prefix | ansible.utils.ipaddr('-2') | ansible.utils.ipaddr('address') }}"
        nameservers: "{{ nameservers }}"
        net:
          net0: 'virtio,bridge={{ prefix_to_bridge[prefix] }}'
        searchdomains: "{{ searchdomains }}"
        update: true
        update_unsafe: true
        # state: started

    # attempting to start the vm in the configure task resulted in the configruation not applying
    - name: start vm
      community.proxmox.proxmox_kvm:
        vmid: "{{ cloned_vm.vmid }}"
        state: started