---
- name: Zabbix Service Verification
  ansible.builtin.systemd_service:
    name: zabbix-server.service
    state: started

- name: Zabbix DB Service Verification
  ansible.builtin.systemd_service:
    name: postgresql.service
    state: started

- name: nginx Service Verification
  ansible.builtin.systemd_service:
    name: nginx.service
    state: started
