- name: Zabbix Service Verification
  ansible.builtin.systemd_service:
    name: zabbix-server.service
    state: started

- name: Zabbix DB Service Verification
  ansible.builtin.systemd_service:
    name: mariadb.service
    state: started

- name: Apache Service Verification
  ansible.builtin.systemd_service:
    name: apache2.service
    state: started