---
domains:
  lab.lan:
    - name: "pve"
      type: "A"
      value: "192.168.0.200"
    - name: "dns-01"
      type: "A"
      value: "10.0.0.101"
    - name: "dns-02"
      type: "A"
      value: "10.0.0.102"
    - name: "gns03-01"
      type: "A"
      value: "10.1.0.203"
    - name: "pfsense-01"
      type: "A"
      value: "192.168.0.253"
    - name: "ca-01"
      type: "A"
      value: "10.0.0.104"
    - name: "zabbix-01"
      type: "A"
      value: "10.0.0.105"
    - name: "docker-01"
      type: "A"
      value: "10.0.0.106"
    - name: "staging-01"
      type: "A"
      value: "10.0.0.51"
    - name: "cml-01"
      type: "A"
      value: "10.0.0.103"
    - name: "r1"
      type: "A"
      value: "10.0.0.11"
    - name: "r2"
      type: "A"
      value: "10.0.0.12"
    - name: "r3"
      type: "A"
      value: "10.0.0.13"
    - name: "r4"
      type: "A"
      value: "10.0.0.14"
    - name: "ns1"
      type: "CNAME"
      value: "dns-01"
    - name: "ns2"
      type: "CNAME"
      value: "dns-02"
    - name: "ejbca-node1"
      type: "CNAME"
      value: "ca-01"
    - name: "lab.lan."
      type: "CAA"
      value: "ca-01.lab.lan"
    - name: "dhcp-01"
      type: "A"
      value: "10.1.0.10"
    - name: "sandbox-01"
      type: "A"
      value: "10.0.0.107"
    - name: "staging-02"
      type: "A"
      value: "10.0.0.50"
  dev.lab.lan:
    - name: "dns-03"
      type: "A"
      value: "10.2.0.101"
    - name: "dns-04"
      type: "A"
      value: "10.2.0.102"
    - name: "dhcp-02"
      type: "A"
      value: "10.2.0.10"
    - name: "docker-02"
      type: "A"
      value: "10.2.0.106"
